version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=zdsiadbs_db
      - DB_USER=rholdxz@gmail.com
      - DB_PASS=#Roldan09219872934
    depends_on:
      - db

  db:
    image: postgres:alpine3.19
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=zdsiadbs_db
      - POSTGRES_USER=rholdxz@gmail.com
      - POSTGRES_PASSWORD=#Roldan09219872934

  pgadmin:
    image: dpage/pgadmin4:snapshot
    environment:
      - PGADMIN_DEFAULT_EMAIL=rholdxz@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=#Roldan09219872934
    ports:
      - "5050:80"

volumes:
  dev-db-data: