# Generated by Django 4.2.8 on 2023-12-26 10:47

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=15, region='PH'),
        ),
    ]
