# Generated by Django 4.2.8 on 2023-12-26 11:18

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_contact_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'required': 'Please enter a valid phone number (e.g. 09123456789 or +639123456789).'}, help_text='Enter a valid phone number (e.g. 09123456789 or +639123456789).', max_length=15, region='PH'),
        ),
    ]
